stages:
  - build
  - test

variables:
  CCACHE_BASEDIR: ${CI_PROJECT_DIR}
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  BUILD_DIR: ${CI_PROJECT_DIR}/build

.buildcache: &buildcache
  cache:
    key: ${CI_JOB_NAME}-cache
    paths:
      - ccache/
      - build/

.build: &build
  image: registry.gitlab.com/vengi/build-images/${CI_JOB_NAME}:master
  stage: build
  script:
    - cmake -H. -B${BUILD_DIR}
    - make -j 4 all -C ${BUILD_DIR}

osx-x86_64:
  <<: *buildcache
  <<: *build

mxe:
  <<: *buildcache
  <<: *build

debian:
  <<: *buildcache
  <<: *build

.test:
  variables:
    POSTGRES_DB: enginetest
    POSTGRES_USER: engine
    POSTGRES_PASSWORD: engine
    DB_HOST: postgres
    DB_USER: engine
    DB_PASSWORD: engine
    DB_NAME: enginetest
  services:
    - postgres:latest
  stage: test
  dependencies:
    - build
  script:
    - make -j 4 tests-run
  artifacts:
    reports:
      junit: build/*/gtest.xml
