site_name: vengi - voxel engine and its tools
site_author: Martin Gerhardy
site_description: Voxel editor for linux windows and macosx
docs_dir: docs
site_dir: build/docs
repo_url: https://github.com/mgerhardy/engine
repo_name: GitHub

theme:
  custom_dir: docs/theme
  name: readthedocs
  highlightjs: true
  hljs_languages: [cpp]

markdown_extensions:
  - toc:
      toc_depth: 2

nav:
  - README.md
  - Basics:
      - Dependencies.md
      - Compilation.md
      - Configuration.md
      - Formats.md
      - CHANGELOG.md
  - VoxEdit:
      - voxedit/Index.md
      - voxedit/LUAScript.md
  - Client/Server:
      - server/Index.md
      - server/Setup.md
  - Tools:
      - VoxConvert: voxconvert/Index.md
      - Thumbnailer: thumbnailer/Index.md
      - MapView: mapview/Index.md
  - Development:
      - Visual Tests: VisualTests.md
      - Game Design: GameDesign.md
      - Shader integration: ShaderTool.md
      - Compute Shader integration: ComputeShaderTool.md
      - Persistence: Persistence.md
      - Animations: Animations.md
      - Attributes: Attributes.md
      - Network: Network.md
      - AI development: AIRemoteDebugger.md
  - Test applications:
      - TestAnimation: TestAnimation.md
      - Traze: Traze.md
      - VisualTests.md
