site_name: vengi - voxel tools
site_author: Martin Gerhardy
site_description: Voxel editor for linux windows and macosx
docs_dir: docs
site_dir: build/docs
repo_url: https://github.com/vengi-voxel/vengi
repo_name: GitHub

extra_css:
  - css/vengi.css

theme:
  custom_dir: docs/theme
  name: material
  highlightjs: true
  hljs_languages: [cpp, lua]

markdown_extensions:
  - toc:
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgerhardy
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@mgerhardy
    - icon: fontawesome/brands/discord
      link: https://vengi-voxel.de/discord

nav:
  - README.md
  - FAQ.md
  - CHANGELOG.md
  - Basics:
      - Configuration.md
      - Formats.md
      - LUAScript.md
      - Palette.md
      - Material.md
      - Meshing.md
      - Voxelization.md
      - Translation.md
  - VoxConvert:
      - voxconvert/Index.md
      - voxconvert/Usage.md
      - voxconvert/Configuration.md
      - voxconvert/Examples.md
      - voxconvert/Screenshots.md
  - VoxEdit:
      - voxedit/Index.md
      - voxedit/Features.md
      - Usage:
          - voxedit/usage/SceneAndEditMode.md
          - voxedit/usage/ReferencePosition.md
          - voxedit/usage/Brushes.md
          - voxedit/usage/Modifiers.md
          - voxedit/usage/Assets.md
          - voxedit/usage/Camera.md
          - voxedit/usage/Console.md
          - voxedit/usage/GameMode.md
          - voxedit/usage/LSystem.md
          - voxedit/usage/Memento.md
          - voxedit/usage/NodeInspector.md
          - voxedit/usage/Palette.md
          - voxedit/usage/Renderer.md
          - voxedit/usage/SceneView.md
          - voxedit/usage/Scripts.md
          - voxedit/usage/Animations.md
          - voxedit/usage/Tools.md
          - voxedit/usage/Viewport.md
          - voxedit/usage/ViewModes.md
          - voxedit/usage/Network.md
      - voxedit/Controls.md
      - voxedit/Configuration.md
      - voxedit/Animation.md
      - voxedit/Screenshots.md
  - PalConvert:
      - palconvert/Index.md
      - palconvert/Usage.md
      - palconvert/Examples.md
  - Thumbnailer:
      - thumbnailer/Index.md
      - thumbnailer/Usage.md
      - thumbnailer/Examples.md
  - Blog:
      - blog/devlog_26_01.md
      - blog/devlog_25_12.md
      - blog/devlog_25_11.md
      - blog/devlog_25_10.md
      - blog/devlog_25_09_2.md
      - blog/devlog_25_09.md
      - blog/devlog_25_08_2.md
      - blog/devlog_25_08.md
  - Developers:
      - Dependencies.md
      - Compilation.md
      - Basic: Basics.md
      - Visual Tests: VisualTests.md
      - Shader integration: ShaderTool.md
